name: "Azure Resource Manager (ARM) Template Deployment JS"
description: "Use this GitHub Action task deploy an Azure Resource Manager (ARM) template"
inputs:
  resourceGroupName:
    description: "Provide the name of a resource group."
    required: true
  templateLocation:
    description: "Specify the path to the Azure Resource Manager template."
    required: true
  deploymentMode:
    description: "Incremental (only add resources to resource group) or Complete (remove extra resources from resource group)."
    required: false
    default: Incremental
  deploymentName:
    description: "Specifies the name of the resource group deployment to create."
    required: false
  parameters:
    description: "Supply deployment parameter values."
    required: false
branding:
  color: orange
  icon: package
runs:
  using: "node12"
  main: "dist/index.js"
