on:
  [push]

name: build-release

jobs:
  build:
    name: build-release
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code
        uses: actions/checkout@master

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - run: npm i -D @zeit/ncc
      - run: npm install
        
      
      - name: Build Action
        run: |
          npm i -D @zeit/ncc
          npm install --production
          tsc
          ncc build src/main.js
          
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Add changes" -a

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

    
          

